### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cbess** [alexdrone/ios-realtimeblur#1]
What is the license for this code?

**Comment by akashivskyy** [comment]
:+1:

**Dear owner,** I recommend [choosealicense.com](http://choosealicense.com) if you don't know what to choose.

**Comment by cbess** [comment]
That's an awesome link sir.

**Comment by alexdrone** [comment]
Awesome link :D 
The license is now MIT

**Comment by cbess** [comment]
Please update repository with a LICENSE file, or at least put in in the readme.

**Comment by cbess** [comment]
@alexdrone added simple pull request #7
