### ISSUE TITLE
CGContextTranslateCTM error when poping UIView

### ISSUE THREAD

**Issue by lucaslain** [alexdrone/ios-realtimeblur#15]
Hello, 

I've used your library to implement a blur on a UIImageView (awesome work). The thing is that when I go back to the previous view, this error shows up:

"CGContextTranslateCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update."

I think it's a problem within the function renderLayerWithView because the context is not present anymore. 

I'll try to fixit myself. Just letting you know! thanks!

**Comment by MikeDaniel18** [comment]
Get any further with this? Just encountered the problem myself.

Mike

EDIT: Should have looked around before posting. Perfect asnwer here: https://github.com/alexdrone/ios-realtimeblur/issues/2

**Comment by MikeDaniel18** [comment]
Very good, thank you mdb983. Works well.

**Comment by lucaslain** [comment]
Thanks!
