### ISSUE TITLE
Blurring MKMapView in background without affecting whats in front of it

### ISSUE THREAD

**Issue by davidrichard23** [alexdrone/ios-realtimeblur#21]
Im trying to blur a map that serves as a background to my profile page. Its working fine except that it takes what I have in front(that I dont want blurred), makes a copy, shifts it down, and blurs it too. Is there a way to avoid this? Here is a screenshot. The most noticable is the profile picture
![photo sep 24 7 36 30 pm](https://f.cloud.github.com/assets/5532434/1205387/00559580-2580-11e3-9ec3-20d6e1860e6e.png)

**Comment by alexdrone** [comment]
Fixed :)

**Comment by davidrichard23** [comment]
thanks!
